### ISSUE TITLE
Сайт umori.li не доступен

### ISSUE THREAD

**Issue by nikolaev-rd** [sagol/umori.li#1]
Привет!
Я используют твой сайт-агрегатор umori.li через REST API в своем чат-боте (выдаю случайную цитату/шутку по запросу), и начал замечать что он периодически становится недоступен. Похоже, домен umori.li просто перестает резолвится (причем отовсюду), через некоторое время всё снова ОК. 
Вот что показывают сервисы whois по этому домену в проблемный момент (например, прямо сейчас):
### Информация о домене UMORI.LI

**По данным WHOIS.NIC.LI:**
```
The number of requests per client per time interval is restricted. You have exceeded this limit. 
Please wait a moment and try again.
```

Видимо, это ограничение сервиса, на котором размещен сайт.

**Comment by sagol** [comment]
Привет.
Ок, я посмотрю. Видимо, количество пользователей выросло и наткнулось на
какие-то ограничения heroku.

6 мая 2017 г., 20:30 пользователь Roman Nikolaev <notifications@github.com>
написал:

**Comment by sagol** [comment]
Как временное решение, можно использовать длинный адрес
http://umorili.herokuapp.com

10 мая 2017 г., 13:03 пользователь Taras Baranyuk <taras.baranyuk@gmail.com>
написал:

**Comment by sagol** [comment]
DNS резолвится. Как оказалось - умер DNS-хостер и пришлось переехать на
другой.

10 мая 2017 г., 13:54 пользователь Taras Baranyuk <taras.baranyuk@gmail.com>
написал:
